version: '3'

services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: svist7890
      MYSQL_DATABASE: search_engine
      MYSQL_USER: root
      MYSQL_PASSWORD: svist7890

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/search_engine
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: svist7890
